### ISSUE TITLE
qemu-system-x86_64: Display 'sdl' is not available.

### ISSUE THREAD

**Issue by jules35** [arindas/mac-on-linux-with-qemu#20] opened 2021-08-25 15:21 UTC
hi 
i try on ubuntu
all is ok but i cant lanch it 
i have an error 
qemu-system-x86_64: Display 'sdl' is not available.

what i have to do?

kind regards

**Comment by arindas** [comment] 2021-08-25 16:25
Duplicate of #5

**Closed by arindas** 2021-08-25 16:25 UTC
