### ISSUE TITLE
Display 'sdl' is not available 

### ISSUE THREAD

**Issue by laTruffe79** [arindas/mac-on-linux-with-qemu#14] opened 2021-08-25 07:19 UTC
This error appears when I launch it on debian 10.

**Comment by littlejuice** [comment] 2021-08-25 07:28
Hello, same issue there. Thanks for your help !

**Comment by arindas** [comment] 2021-08-25 08:01
Duplicate of #5

**Closed by arindas** 2021-08-25 08:01 UTC

**Comment by laTruffe79** [comment] 2021-08-25 15:39
Does not work with mentionned workarounds on Debian 10 / gnome
